### ISSUE TITLE
Getting error 520 in botsapp official website

### ISSUE THREAD

**Issue by aritroCoder** [BotsAppOfficial/BotsApp#103]
![image](https://user-images.githubusercontent.com/92646038/154194183-3cfc295e-84f9-49e4-804e-e4c07d608d82.png)

Please help to fix it

**Comment by Prince-Mendiratta** [comment]
Hi @aritroCoder.The issue has been resolved, you can visit the site now.

**Comment by anteac** [comment]
Same issue right now
