### ISSUE TITLE
Enable commands for yourself

### ISSUE THREAD

**Issue by Gurdt1** [BotsAppOfficial/BotsApp#131]
Hi There,

I updated to the last version but the older version it was possible to text to yourself and test the commands.
But it's not possible any more, where can I change the code so I can send commands to my self?

**Comment by Prince-Mendiratta** [comment]
Hi @Nagrom33. In the latest version, it is simply not possible to run commands in the chat for your own number. I'd suggest you to create a new group that you can have for your personal testing.

**Comment by Gurdt1** [comment]
I created a group, and delete all the users. Now I can go testing. Thanks for your fast response!
