### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isEnabled')

### ISSUE THREAD

**Issue by harleydica** [BotsAppOfficial/BotsApp#136]
when I try to .help promote on the info terminal an error appears like `TypeError: Cannot read properties of undefined (reading isEnabled')` and on whatsapp replies "Something went wrong. the error has ben logged in log chats"

**Comment by Prince-Mendiratta** [comment]
Hi @harleydica. Thank you for reporting this, I will take a look.
