### ISSUE TITLE
add the download module feature

### ISSUE THREAD

**Issue by harleydica** [BotsAppOfficial/BotsApp#139]
when I added the download module feature I got some problems, and after there were no problems, the module I added didn't react at all. Can the developers add a youtube download feature or something else? I think this will be the attraction of other users. thank you

**Comment by Prince-Mendiratta** [comment]
@harleydica I'm afraid I didn't quite understand what you're requesting for exactly, do you mind elaborating further?

**Comment by Prince-Mendiratta** [comment]
Closing since no response.
