### ISSUE TITLE
HOW TO RUN UBUNTU

### ISSUE THREAD

**Issue by Suryapardana** [BotsAppOfficial/BotsApp#155]
not working install yarn

**Comment by Prince-Mendiratta** [comment]
Hi @Suryapardana, what kind of issue are you facing? Can you elaborate?

**Comment by Suryapardana** [comment]
> Hai@Suryapardana, masalah apa yang Anda hadapi? Bisakah Anda menguraikan?

![Screenshot_20220915-161148_Termius](https://user-images.githubusercontent.com/47344288/190374357-d655d690-ba23-4004-b202-0c79152670b9.jpg)

**Comment by Prince-Mendiratta** [comment]
You seem to have installed the wrong version of yarn. Do the following to remove it -

`sudo apt remove yarn`

To install yarn correctly, run the following commands -
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update && sudo apt install yarn

yarn
```

**Comment by Suryapardana** [comment]
done thanks
