### ISSUE TITLE
Malfunctioning

### ISSUE THREAD

**Issue by Kokuba** [BotsAppOfficial/BotsApp#79]
It's no more responding or does it close?

**Comment by Prince-Mendiratta** [comment]
Hi @Kokuba. Can you explain more about the issue you're facing? Have you deployed your own userbot or are you referring to the demo bot?

**Comment by Kokuba** [comment]
Ohh I think am using the demo
But I followed everything according to the tutorial

**Comment by Kokuba** [comment]
Because mine has stopped working
And my sudos are complaining

**Comment by Prince-Mendiratta** [comment]
If you've deployed your own and it's not working, try following these steps -

1. Go to https;//mybotsapp.com
2. Login
3. Click on your app
4. Turn the status off
5. Click on apply changes
6. Click on the app again
7. Turn the status on
8. Click on apply changes

This should restart the bot.

**Comment by Kokuba** [comment]
Thanks 👍 it worked

**Comment by Kokuba** [comment]
Another problem, everybodybody on the group is using the bot but i set it to private. Why is it not working in private

**Comment by Prince-Mendiratta** [comment]
Make sure that the WORK_TYPE variable is set to **private**,  case sensitive. It should work only for you in that case.

**Comment by Kokuba** [comment]
If it is in private can it work for my sudos?

**Comment by Prince-Mendiratta** [comment]
Yes, if you want some specific people to be able to use your bot while it is private, you can add them to sudo.

**Comment by Prince-Mendiratta** [comment]
Yes, if you want some specific people to be able to use your bot while it is private, you can add them to sudo.

**Comment by Kokuba** [comment]
Thanks 👍

**Comment by Kokuba** [comment]
Please how do I add a sudo, if there no function for it?

**Comment by Kokuba** [comment]
No answer? @Prince-Mendiratta

**Comment by Mastersam07** [comment]
Go to bot settings, add the numbers along with their country code separated by commas.

**Comment by Kokuba** [comment]
Thanks 👍
