### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Kokuba** [BotsAppOfficial/BotsApp#80]
We also need it to perform some little gaming options to make it more fun.

**Comment by Prince-Mendiratta** [comment]
Hi @Kokuba . What kind of gaming options are you looking for? Can you provide an example?

**Comment by Kokuba** [comment]
A game that teaches coding, or any other educative game. I have one AVE encountered be4 but I don't know how to explain it.

**Comment by Prince-Mendiratta** [comment]
Okay, we'll explore that and see if we can do anything that's user friendly enough.

**Comment by Kokuba** [comment]
Nice 👍
