### ISSUE TITLE
App deletion

### ISSUE THREAD

**Issue by ItsAshu007** [BotsAppOfficial/BotsApp#97]
How to delete the created the botsapp apps
please help

**Comment by Prince-Mendiratta** [comment]
# Deleting an app
Go to heroku.com
Login
Click on the app you want to delete
Switch to desktop mode
Click on settings
Scroll to the bottom
Click on delete app
Write the app's name
Delete app

**Comment by ItsAshu007** [comment]
Is the app safe?

**Comment by Prince-Mendiratta** [comment]
Yes, the code is open source, you can directly check out what is happening under the hood.

**Comment by ItsAshu007** [comment]
Okay
Thanx
Its a great app
I will surely spread it 🔥

**Comment by Prince-Mendiratta** [comment]
Welcome.

Thanks! :D

**Comment by ItsAshu007** [comment]
Can you please include the command to spam a message!!

**Comment by Prince-Mendiratta** [comment]
Hey, we've deliberately not added handlers for spamming. They increase the chances of the account getting banned.

**Comment by ItsAshu007** [comment]
What closed?

**Comment by Prince-Mendiratta** [comment]
@ItsAshu007 Once your query is resolved on Github, the issue should be closed.
